# Generated by Django 4.0.5 on 2022-06-30 05:32

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eliteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedposts',
            fields=[
                ('feed_id', models.UUIDField(default=uuid.UUID('0755f523-546a-4748-8fe6-e83a0da99733'), primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=200)),
                ('postimage', models.ImageField(upload_to='post_images')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
