# Generated by Django 4.0.5 on 2022-06-30 05:38

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eliteapp', '0002_feedposts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedpost',
            fields=[
                ('feed_id', models.UUIDField(default=uuid.UUID('6dfdf4ba-03cf-4ce5-98e7-448d32373ab2'), primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=200)),
                ('postimage', models.ImageField(upload_to='post_images')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Feedposts',
        ),
    ]
