# Generated by Django 4.0.5 on 2022-06-30 10:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eliteapp', '0003_feedpost_delete_feedposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='user',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='feed_id',
            field=models.UUIDField(default=uuid.UUID('f6a393d9-a3d0-48d9-8bb1-ce88acf0741f'), primary_key=True, serialize=False),
        ),
    ]
