# Generated by Django 4.0.5 on 2022-06-30 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eliteapp', '0004_feedpost_user_alter_feedpost_feed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='feed_id',
            field=models.UUIDField(default=uuid.UUID('15f295ca-e6a8-4e1e-ae0a-26f86b74b847'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
