# Generated by Django 4.0.5 on 2022-06-30 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eliteapp', '0005_alter_feedpost_feed_id_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='feed_id',
            field=models.UUIDField(default=uuid.UUID('2bcc0cde-5ffe-49d1-a32b-570a254cd8af'), primary_key=True, serialize=False),
        ),
    ]
